package org.mitre.simply.encryption;

import javax.crypto.spec.SecretKeySpec;

import org.apache.commons.lang3.CharEncoding;

public interface PwdKeyGenerator {

	public static final KeyLengthType DEFAULT_KEY_LENGTH = KeyLengthType.SHORT;
	
	public static final String DEFAULT_KEY_ALGORITHM = "AES";
	
	public static final String DEFAULT_CHAR_ENCODING =  CharEncoding.UTF_8; 
		
	/**
	 * This method takes a password and a key output length which are used to 
	 * generate appropriate encryption key. 
	 * 
	 * @param pwd value from which the encryption key is generated
	 * @param keyLength  length of key output in bits  
	 * @return
	 */
	public SecretKeySpec deriveKey(String pwd);
	
	/**
	 * Returns secret key generated by the deriveKey method. 
	 * 
	 * @return 
	 */
	public SecretKeySpec getSecretKey();
		
}
